# https://docs.travis-ci.com/user/languages/python/
language: python

python:
- "3.5"

# https://github.com/LiliC/travis-minikube/blob/master/.travis.yml

sudo: required

env:
- CHANGE_MINIKUBE_NONE_USER=true

  # --bootstrapper=localkube comes from
  # https://github.com/kubevirt/containerized-data-importer/issues/93
  # and
  # https://github.com/kubernetes/minikube/issues/2704
before_script:
- sudo apt-get update
- sudo apt-get install -y coreutils
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- sudo minikube start --bootstrapper=localkube --vm-driver=none
- minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
- kubectl cluster-info
