name = config['name']

rule rulename1:
     input:
        "alpha.txt"

rule target1:
     output:
        "alpha.txt"
     shell:
        "echo alpha {name} > {output}"

rule target2:
     output:
        "gamma.txt"
     shell:
        "echo gamma {name} > {output}"
